from pathlib import Path
import json,html,datetime,re
R=Path(r'C:\Projects\paopao\APIReplaceReports\bubblosaicpmge-20260916')
def load(n):return json.loads((R/n).read_text(encoding='utf-8-sig').lstrip('\ufeff'))
def esc(v):return html.escape(str(v) if v is not None else '—')
def pretty(v):return '<pre>'+esc(json.dumps(v,ensure_ascii=False,indent=2))+'</pre>'
def table(headers,rows,classes=''):
    return '<div class="table-wrap"><table class="'+classes+'"><thead><tr>'+''.join('<th>'+esc(x)+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(v)+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def badge(s):return '<span class="badge '+('warn' if any(k in s for k in ['Unresolved','Mismatch','Skipped','NoCaller']) else 'ok')+'">'+esc(s)+'</span>'
def section(id,title,content):return f'<section id="{id}"><h2>{title}</h2>{content}</section>'
a=load('api-audit.json');attr=load('attribution-audit.json');comm=load('communication.json');param=load('parameter-validation.json');channel=load('channel-validation.json');contract=load('method-contract.json');comp=load('compile.json');ob=load('obfuz-validation.json');prefix=load('obfuz-prefix.json');files=load('file-comparison.json');paths=load('path-validation.json')
assert comp[0]['exit_code']==0 and comp[1]['exit_code']==0
assert comm['business']['success'] and contract['status']=='Passed' and channel['status']=='Passed'
assert len(a['Unresolved'])==3 and len(a['SwaggerTypeMismatch'])==3
parts=[]
parts.append(section('outcome','执行结果',f'''<div class="notice">已确认项已完成验证；保留 3 项 Unresolved，未将其标为替换成功。当前工程中的接口映射和发行参数已符合本次输入，因此无需重复改写业务源码。</div><div class="metrics"><div><b>18 / 19</b><span>精确路径与 Tag 匹配</span></div><div><b>212 / 214</b><span>DTO 属性匹配；2 项保留</span></div><div><b>19 / 19</b><span>实际归因 JSON 键匹配</span></div><div><b>0 错误</b><span>运行时 + Editor 编译</span></div><div><b>HTTP 200</b><span>AppConfig 加密通讯成功</span></div></div><p>本次实际内容变更：<code>ProjectSettings/Obfuz.asset</code> 的名称前缀 <code>{esc(prefix['old'])}</code> → <code>{esc(prefix['new'])}</code>。ChannelConfig 使用项目自己的序列化器写回，写回前后字节一致。{contract['source_file_count']} 个 C# 源文件保持原样，保留工作区已有修改。</p><p>输入严格使用本次消息；未读取 ParamTemp.md 或历史执行报告。Swagger 使用指定目录内有效的本地缓存，未刷新。</p>'''))
urows=[]
for u in a['Unresolved']:
    if u.get('kind')=='ExactPathTagMismatch':
        urows.append([esc('AccountModuleCfg.order_name'),'<code>'+esc(u['oldPath'])+'</code>',esc('不属于 FruitTileMatch；没有运行时调用'),esc('保留原路径；需要明确目标 Tag 下的路径，不能按相似名称猜测')])
    else:
        refs='；'.join(Path(x['file']).name+':'+str(x['line'])+' '+x.get('method','') for x in u.get('businessReferences',[]))
        urows.append([esc(u['dto']+'.'+u['field']),'<code>'+esc(u['old'])+'</code>',esc('Swagger 无对应字段；引用：'+refs),esc('保留字段、JsonProperty 和业务调用；没有改名、删字段或改方法')])
parts.append(section('unresolved','保留待确认项',table(['本地项','当前路径 / JSON 键','原因与证据','本次处理'],urows)))
parts.append(section('parameters','发行参数归一化与写回', '<p>游戏类型：<b>真假混</b>，对应 <code>incomeRate = 1</code>。国家 <code>NONE</code> 映射到现有枚举 <code>None (0)</code>；默认国家、横幅、开屏输入为空，跳过并保留原值。密钥仅显示核验结果。</p>'+table(['原始参数名','标准参数名','目标字段','修改前','修改后','结果'],[[esc(x[k]) for k in ('raw','normalized','target','before','after')]+[badge(x['status'])] for x in param['rows']])))
endpointrows=[]
for e in a['endpoints']:
    endpointrows.append([esc(e['constant']),'<code>'+esc(e['oldPath'])+'</code>','<code>'+esc(e['newPath'])+'</code>',esc(e.get('exactTag')),badge(e['status']),esc('; '.join(str(c.get('line')) for c in e.get('calls',[])) or '无调用')])
parts.append(section('paths','接口路径与实际调用',table(['配置常量','修改前','修改后','精确 Tag','结果','AccountModule.cs 调用行'],endpointrows)+'<p><code>/Api/Match/Name</code> 仅存在已匹配的配置路径；项目没有对应调用或 DTO，因此未新增方法。<code>order_name</code> 同样无调用，但其路径属于其它 Tag。</p>'))
fields=a['fieldMappings']; frows=[]
for f in fields:
    frows.append([esc(f['dto']+'.'+f['field']),esc(f['csharpType']),'<code>'+esc(f['old'])+'</code>','<code>'+esc(f['new'])+'</code>',esc(f['jsonPath']),esc((f.get('swaggerProperty') or {}).get('description','未定义')),badge(f['status'])])
parts.append(section('fields','DTO 字段与反向字段检查',f'<p>{a["summary"]["dtoClasses"]} 个 DTO，{len(fields)} 个属性。212 个键已精确一致、2 个保留待确认；目标 Swagger 字段无遗漏。本次新增 / 删除 DTO 字段：0；JSON 属性替换：0。字段名、类型和业务引用不变。</p><input id="fieldSearch" aria-label="筛选字段" placeholder="筛选 DTO、字段、JSON 键或状态…">'+table(['DTO / C# 字段','原 C# 类型（保留）','旧 JSON 键','新 JSON 键','JSON 路径','Swagger 含义','结果'],frows,'field-table')+'<details><summary>按接口查看递归请求 / 响应字段集合（含数组与嵌套对象）</summary>'+''.join('<details><summary>'+esc(e['constant']+' '+e['oldPath'])+'</summary>'+pretty({'requestSchema':e.get('requestSchema'),'responseSchema':e.get('responseSchema'),'requestFields':e.get('requestFields',[]),'responseFields':e.get('responseFields',[])})+'</details>' for e in a['endpoints'])+'</details>'))
parts.append(section('attribution','CreateFromJson 与实际归因 payload', '<p><b>静态检查通过，未在 Unity 中运行真实归因序列化或向服务器发送归因事件。</b>已覆盖 <code>#if BIZZA_ENABLE_ADJUST</code>，沿实际回调、请求构造、JsonConvert.SerializeObject 和 HTTP 调用核对。19 个根级键均已匹配，无遗漏、重复或旧键残留；无嵌套对象或数组。成本空值处理、时间秒单位、默认值和取值表达式均不变。</p>'+pretty(attr['callChain'])+table(['JSON 路径 / 字段','旧键 → 新键','证据'],[[esc(m.get('jsonPath',m.get('field',m.get('oldKey',m.get('old',''))))),esc(str(m.get('oldKey',m.get('old','')))+' → '+str(m.get('newKey',m.get('new','')))),pretty(m)] for m in attr['mapping']])+'<details><summary>实际构造 payload 检查详情</summary>'+pretty(attr['actualPayloadChecks'])+'</details>'))
parts.append(section('contract','方法契约与提现例外',f'<p><b>通过。</b>修改前后 {contract["source_file_count"]} 个 Assets / Packages C# 文件逐字节相同；AccountModule 另与并行审计前的原始备份核对一致。本次确认需要变更的请求键清单为空，因此没有需要排除的合法键名 token。方法声明、方法体、局部函数、回调/委托签名、泛型参数、调用位置与参数顺序全部保持。</p><p>Fake 提现 DTO 13 字段、Real 11 字段及其构造方法赋值一致；未发生参数增减，因此未触发提示词中的提现方法修改例外。</p><details><summary>提现字段及赋值逐项检查</summary>'+pretty(a['withdrawalExceptionChecks'])+'</details>'+table(['接口','Swagger 根类型','保留的本地类型','保留的调用位置'],[[esc(x['path']),esc(x['swagger']),esc(x['local']),esc(x['method']+' / AccountModule.cs:'+str(x['line']))] for x in a['SwaggerTypeMismatch']])+'<p>以上三项均记录为 <code>SwaggerTypeMismatch</code>。继续按 Swagger 的 items / $ref 检查 DTO 字段，但不以文档根容器覆盖本地已验证契约。</p>'))
parts.append(section('channel','ChannelConfig 二进制结果','<p><b>通过。</b>一次性工具直接编译当前项目的 <code>ChannelConfigBinarySerializer.cs</code> 并调用 Deserialize / Serialize。使用公开字段与属性更新参数；没有文本替换二进制，也没有新增反射。</p>'+table(['校验','结果'],[[esc(k),esc(v)] for k,v in channel.items()])+ '<p>原始数据备份保存在 <code>before/Assets/StreamingAssets/ChannelConfig.bytes</code>，所有非目标序列化字段、空输入项均保持。当前文件 244 字节，写回前后 SHA-256 一致。</p>'))
parts.append(section('obfuz','Obfuz 配置与生成资源',table(['项','修改前','修改后 / 验证'],[[esc('混淆程序集'),esc('Assembly-CSharp'),esc('Assembly-CSharp')],[esc('静态 / 动态密钥'),esc('com.webpack.picturemerge'),esc('相同；现有 KeyGenerator.GenerateKey 验证两个 1024 字节文件完全匹配')],[esc('代码生成密钥'),esc('picturemerge'),esc('相同；现有 VirtualMachineCodeGenerator.ValidateMatch 验证 256 操作码虚拟机匹配')],[esc('名称前缀'),esc(prefix['old']),esc(prefix['new']+'；本次密码学随机选取三个小写英文字母')]])+'<p>密钥文件与生成代码已匹配，不需重建相同产物。仅更新随机名称前缀。</p>'))
parts.append(section('compile','编译结果',table(['程序集','结果','错误','警告','验证范围'],[[esc(x['assembly']),badge('Passed' if x['exit_code']==0 else 'Failed'),esc(len(x['errors'])),esc(x['warning_count']),esc(x['scope'])] for x in comp])+'<p>使用 Unity 2022.3.62f3 自带 Roslyn 与工程生成的编译响应文件（含 Android、Editor、BIZZA_ENABLE_ADJUST 宏），编译产物写入本报告目录。Editor 编译引用本次生成的运行时程序集。96 条现有警告留在日志中；本次未改 C# 源码。</p><p>未执行 Unity batchmode、APK / AAB、IL2CPP 或真机运行；上述未执行项不计为失败，也不宣称已验证。</p><p><a href="Assembly-CSharp.compile.log">运行时编译日志</a> · <a href="Assembly-CSharp-Editor.compile.log">Editor 编译日志</a></p>'))
other=comm['decryption']['payload']
parts.append(section('communication','API 通讯与 Other 参数',f'<p><b>已执行并成功。</b>时间：{esc(comm["testedAt"])}。<code>POST {esc(comm["endpoint"])}</code> 读取现有配置；HTTP <b>200</b>，业务码 <b>200</b>，<code>message = success</code>。采用项目原版 XXTEA、UTF-8 JSON、Base64 的 sign 包装和 X-Bundle 请求头，响应解密及 JSON 解析成功。</p>'+pretty({'requestFields':comm['requestFields'],'requestHeaders':comm['requestHeaders']})+table(['现有 Other 参数键','服务端值','结果'],[[esc(k),esc(other[k]),badge('VerifiedUnchanged')] for k in comm['business']['expectedConfigKeys']])+'<p>六个业务使用的键均存在，无需替换 Other 常量；额外返回 <code>next_day</code> 不触发新增业务逻辑。没有发起登录建号、真实提现、收益、广告或归因上报。其它接口未进行动态通讯验证，原因是缺少测试用户会话或会改变业务状态；其结果为“未执行”。</p><details><summary>脱敏通讯证据</summary>'+pretty(comm)+'</details>'))
parts.append(section('changes','修改前后文件对比',table(['文件','是否内容变化','修改前 SHA-256','修改后 SHA-256'],[[esc(f['file']),esc('是' if f['changed'] else '否'),'<code>'+esc(f['before_sha256'])+'</code>','<code>'+esc(f['after_sha256'])+'</code>'] for f in files])+'<p>比较基线是本次执行前工作区文件，非 Git HEAD；已有未提交修改未被回退。报告、一次性验证工具及编译产物均保存在独立报告目录。</p>'))
parts.append(section('evidence','证据文件与跳过项', '<p>本地 Swagger：<code>'+esc(paths['cache'])+'</code><br>SHA-256：<code>'+esc(paths['sha256'])+'</code></p><ul>'+''.join('<li><a href="'+esc(n)+'">'+esc(n)+'</a></li>' for n in ['api-audit.json','attribution-audit.json','method-contract.json','parameter-validation.json','channel-validation.json','obfuz-validation.json','compile.json','communication.json','file-comparison.json','git-status-before.txt'])+'</ul>'+table(['项目','状态','原因'],[[esc('默认国家、MAX 横幅、MAX 开屏'),badge('Skipped'),esc('本次输入为空，按提示词保留旧值')],[esc('order_name 路径'),badge('Unresolved'),esc('未精确匹配目标 Tag，保留原值')],[esc('两个有引用旧响应字段'),badge('Unresolved'),esc('Swagger 不定义对应字段，禁止通过改业务逻辑删除')],[esc('3 个文档根容器差异'),badge('SwaggerTypeMismatch'),esc('按提示词保护本地方法契约')],[esc('/Name 调用 / DTO'),badge('VerifiedPathNoCaller'),esc('配置已匹配，项目没有调用；未新增实现')],[esc('归因动态序列化 / 真机 / 打包'),esc('未执行'),esc('归因采用静态实际构造路径检查；编译范围见上文')],[esc('其它接口通讯'),esc('未执行'),esc('仅以只读 AppConfig 验证真实域名、应用 ID、密钥、包名与字段通讯')]])))
nav=[('outcome','结果'),('unresolved','待确认'),('parameters','参数'),('paths','路径'),('fields','DTO 字段'),('attribution','归因'),('contract','方法契约'),('channel','ChannelConfig'),('obfuz','Obfuz'),('compile','编译'),('communication','通讯'),('changes','文件对比'),('evidence','证据')]
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f3f6fa;color:#19283e;font:14px/1.65 "Segoe UI","Microsoft YaHei",sans-serif}header{background:#142941;color:white;padding:38px max(28px,calc((100% - 1300px)/2))}header h1{margin:4px 0 12px;font-size:30px}header p{color:#d2deeb;margin:3px 0}.eyebrow{font-size:12px;letter-spacing:2px;color:#77d7c1}nav{position:sticky;top:0;background:#fff;border-bottom:1px solid #d9e2ec;padding:11px 24px;display:flex;gap:18px;flex-wrap:wrap;z-index:2}nav a,a{color:#1264a3;text-decoration:none}a:hover{text-decoration:underline}main{max-width:1356px;margin:26px auto;padding:0 28px}section{scroll-margin-top:90px;background:#fff;border:1px solid #dfe6ef;border-radius:10px;padding:25px;margin-bottom:22px}h2{margin:0 0 17px;font-size:21px}.notice{background:#fff7e5;border-left:4px solid #d99023;padding:14px 17px;border-radius:3px}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin:20px 0}.metrics div{background:#eff7f6;border:1px solid #d2e9e4;border-radius:8px;padding:16px}.metrics b{display:block;font-size:25px;color:#126b59}.metrics span{display:block;color:#536679;font-size:12px}.table-wrap{overflow:auto;width:100%}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#edf2f7;text-align:left;white-space:nowrap}th,td{padding:10px 12px;border:1px solid #e0e6ee;vertical-align:top;overflow-wrap:anywhere}tbody tr:nth-child(even){background:#fafcfe}code{font-family:Consolas,monospace;font-size:12px;color:#263e65;overflow-wrap:anywhere}pre{white-space:pre-wrap;word-break:break-word;font:12px/1.55 Consolas,"Microsoft YaHei",monospace;background:#f3f6fa;border-radius:5px;padding:13px;max-height:500px;overflow:auto;margin:10px 0}.badge{display:inline-block;font-size:11px;line-height:1.5;border-radius:4px;padding:3px 7px;font-weight:600}.ok{background:#e5f4ed;color:#1b6c4c}.warn{background:#fff0d8;color:#8a5b09}details{border:1px solid #dfe5ee;border-radius:6px;padding:10px 13px;margin:14px 0}summary{cursor:pointer;color:#28567a;font-weight:600}input{border:1px solid #b6c8da;border-radius:6px;padding:11px 13px;min-width:320px;margin-bottom:15px;font:inherit}footer{max-width:1300px;margin:20px auto 40px;padding:0 28px;color:#63758b;font-size:12px}@media(max-width:800px){header{padding:26px}header h1{font-size:24px}.metrics{grid-template-columns:repeat(2,1fr)}main{padding:0 12px}section{padding:16px}nav{position:static;gap:12px}input{min-width:0;width:100%}}@media print{nav,input{display:none}body{background:white}main{padding:0}section{break-inside:avoid;border:1px solid #ddd}header{padding:20px}.metrics{grid-template-columns:repeat(5,1fr)}}'''
page='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bubblosaic · API 替换对比报告</title><style>'+css+'</style></head><body><header><div class="eyebrow">PLAYCLOUD · API REPLACE</div><h1>Bubblosaic: Picture Merge</h1><p>API 替换与验证对比报告 · 2026-09-16</p><p>C:\\Projects\\paopao\\BizzaWZ · FruitTileMatch · com.webpack.picturemerge</p></header><nav>'+''.join('<a href="#'+i+'">'+s+'</a>' for i,s in nav)+'</nav><main>'+''.join(parts)+'</main><footer>报告以本次执行的本地源代码、二进制回读、编译输出及 AppConfig 通讯结果为依据。未执行项与待确认项均单独标识，密钥脱敏。</footer><script>document.getElementById("fieldSearch").addEventListener("input",function(){const q=this.value.toLowerCase();document.querySelectorAll(".field-table tbody tr").forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))})</script></body></html>'
# Avoid leaking credentials to the review artifact.
assert 'MergePB@91Saic' not in page
assert 'eEzDO_Ksp3ps7QJkce3MBdxPdGy2Ug0KHSZXf3Wn89mZxIpqFTNbJDa0cvpXa9Ss1lilI2DZclctfNt6GexyJZ' not in page
out=R/'API替换对比报告.html';out.write_text(page,encoding='utf-8')
print(json.dumps({'report':str(out),'bytes':out.stat().st_size,'dto_field_rows':len(fields),'endpoint_rows':len(a['endpoints']),'attribution_rows':len(attr['mapping'])},ensure_ascii=False))
